feat: add README.md file
eZaR-Bot/3Z4R pull request #5
Opened 2022-06-14 19:15 UTC by toolifelesstocode

This pull request is basically adding a README.md file, as we really need it. However, when it comes to styling and not making it look bad, I am not that good at that 😅 which is why I would like to ask someone to review it.

2022-06-14 19:31 UTC, EnokiUN requested changes

2022-06-14 19:31 UTC, EnokiUN commented on README.md
> +- Server-Help (custom welcome & leave messages, auto-role, high-server lockdowns, etc.)
Utility??

2022-06-14 19:34 UTC, toolifelesstocode commented on README.md
> +- Server-Help (custom welcome & leave messages, auto-role, high-server lockdowns, etc.)
> Utility??

As in, I should change "Server-Help" to "Server-Utility"? Or do you mean something else.

2022-06-14 19:39 UTC, ooliver1 requested changes
inline html much

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +    </a>
```suggestion
    [![eZaR Discord guild](https://img.shields.io/discord/906815360492253205?color=dark%20green&logo=discord)](https://ezar.shamdev.xyz/discord)
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +    </a>
```suggestion
    [![eZaR Supported Python versions](https://img.shields.io/badge/Python-3.10-informational?logo=python)](https://ezar.shamdev.xyz)
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +    </a>
```suggestion
    [![eZaR GitHub checks](https://img.shields.io/github/checks-status/eZaR-Bot/3Z4R/main?logo=github)](https://github.com/eZaR-Bot/3Z4R)
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<h2>Features</h2>
```suggestion
## Features
```
not sure what that `h1` is doing

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<h2>Running the bot</h2>
```suggestion
## Running the bot
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<h3>Prerequisites</h3>
```suggestion
### Prerequisites
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +- <a href="https://python.org/downloads">Python 3.8/9/10</a>
```suggestion
- [Python 3.8/9/10](https://python.org/downloads)
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +- <a href="https://python.org/downloads">Python 3.8/9/10</a>
```suggestion
- [Python 3.8/9/10](https://python.org/downloads)
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +- <a href="https://python-poetry.org">Poetry</a>
```suggestion
- [Poetry](https://python-poetry.org)
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +- <a href="https://docker.com">Docker (Optional)</a>
```suggestion
- [Docker (Optional)](https://docker.com)
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +- A <a href="https://mongodb.com">MongoDB</a> cluster
```suggestion
- A [MongoDB](https://mongodb.com) cluster
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +1. Clone the repository by running: <br>
```suggestion
1. Clone the repository by running:  
```
double space should do the trick too

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +2. Copy the contents from /.env.example and fill them in
```suggestion
2. Copy the contents from `.env.example` and fill them in
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<h3>If you are using Docker:</h3>
```suggestion
### If you are using Docker:
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<p>Refer to the steps given in <https://github.com/eZaR-Bot/3Z4R/pulls/4></p
```suggestion
Refer to the steps given in <https://github.com/eZaR-Bot/3Z4R/pulls/4>
```
isnt a website, no need for paragraph tags, md just does that

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<h3>If not:</h3>
```suggestion
### If not:
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +1.1. Open your terminal and run the following:<br>
```suggestion
1. Open your terminal and run the following:  
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<h2>Contributing</h2>
```suggestion
## Contributing
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<p>Thank you for wanting to contribute to eZaR! We appreciate it a ton! In case you don't know how to, here are some steps to help you:
```suggestion
Thank you for wanting to contribute to eZaR! We appreciate it a ton! In case you don't know how to, here are some steps to help you:
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +2. Clone your fork into your IDE using <a href="https://git-scm.com">Git</a> by running: <br>
```suggestion
2. Clone your fork into your IDE using [Git](https://git-scm.com) by running:  
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +4. Make a Pull Request on this respository
```suggestion
4. Make a [Pull Request](https://github.com/eZaR-Bot/3Z4R/compare) on this respository
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<h2>Main Contributors</h2>
```suggestion
## Main Contributors
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<p><a href="https://github.com/ItsNotAlexy">Alexy</a> - Website Developer, Co-Founder</p>
```suggestion
[Sham](https://github.com/toolifelesstocode) - Maintainer, Founder
[Alexy](https://github.com/ItsNotAlexy) - Website Developer, Co-Founder
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<h2>Links</h2>
```suggestion
## Links
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<a href="https://ezar.shamdev.xyz/discord">Discord Support Guild</a>
```suggestion
[Website](https://ezar.shamdev.xyz)

[Invite](https://ezar.shamdev.xyz/invite)

[Discord Support Guild]("https://ezar.shamdev.xyz/discord)
```

2022-06-14 19:39 UTC, ooliver1 commented on README.md
> +<p>Donate - <a href="https://paypal.me/realShamlol">PayPal</a>, <a href="https://patreon.com/ezarbot">Patreon</a></p>
```suggestion
Donate - [PayPal](https://paypal.me/realShamlol), [Patreon](https://patreon.com/ezarbot)
```

2022-06-14 21:19 UTC, ooliver1 requested changes

2022-06-14 21:19 UTC, ooliver1 commented on README.md
> +# Self-hosting eZaR
```suggestion
## Self-hosting eZaR
```

2022-06-14 21:19 UTC, ooliver1 commented on README.md
> +# Contributing
```suggestion
## Contributing
```

2022-06-14 21:19 UTC, ooliver1 commented on README.md
> +# Main Contributors
```suggestion
## Main Contributors
```
also :)

2022-06-14 21:19 UTC, ooliver1 commented on README.md
> +# Main Contributors
```suggestion
## Main Contributors
```
also :3

2022-06-14 21:19 UTC, ooliver1 commented on README.md
> +Donations - [Payapl](https://paypal.com/realShamlol) or [Patreon](https://patreon.com/ezarbot)
```suggestion
Donations - [PayPal](https://paypal.me/realShamlol) or [Patreon](https://patreon.com/ezarbot)
```

2022-06-15 05:28 UTC, toolifelesstocode commented on README.md
> +Donations - [Payapl](https://paypal.com/realShamlol) or [Patreon](https://patreon.com/ezarbot)
I forgor 💀

2022-06-15 16:40 UTC, ooliver1 approved these changes

2022-06-15 17:14 UTC, toolifelesstocode commented
Thanks for the reviews @ooliver1 👍🏼

2022-06-15 17:15 UTC, merged

2022-06-15 17:37 UTC, ooliver1 commented
~~if thats just a readme, god knows what real code would be~~